-- database: ../../f:/SQL/mybase.db
CREATE TABLE ASHISH(ID INT NOT NULL, NAME VARCHAR(20), AGE INT, ADDRESS VARCHAR(20));

INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(1,'ASHISH',18,'MUMBAI');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(2,'RAHUL',19,'DELHI');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(3,'KARAN',20,'PUNE');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(4,'KARTIK',18,'BANGLORE');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(5,'KARAN',18,'CHENNAI');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(6,'KARTIK',21,'PATNA');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(7,'KARAN',22,'MUMBAI');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(8,'KARTIK',19,'DELHI');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(9,'KARAN',31,'PUNE');
INSERT into ASHISH(ID, NAME, AGE, ADDRESS) VALUES(10,'KARTIK',22,'BANGLORE');

SELECT * FROM ASHISH;